apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-server
spec:
  replicas: 1

  selector: # selector utilizado para criar pods <> service
    matchLabels:
      app: mysql-server
      tier: db

  template: # referente ao pod
    metadata:
      labels:
        app: mysql-server
        tier: db

    spec: # referente ao pod
      containers:
      - image: mysql:5.7
        name: mysql-server
        args:
          - "--ignore-db-dir=lost+found"

        env: # kubectl create secret generic mysql-pass --from-literal=password='123456'
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-pass
              key: password

        ports:
        - containerPort: 3306

        volumeMounts: #monta o volume persistente
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql

      volumes: # definição do volume
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: mysql-pv-claim

